In [29]:
# NumPy Exercises

In [30]:
# 1. Import the numpy package under the name np
import numpy as np

In [31]:
# 2. Print the numpy version and the configuration
print(np.__version__)
np.show_config()

2.1.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ofdn91k7/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ofdn91k7/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ofdn91k7/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ofdn91k7/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

In [32]:
# 3. Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
# 4. How to find the memory size of any array
print(f"Memory size of null_vector: {null_vector.nbytes} bytes")

Memory size of null_vector: 80 bytes


In [34]:
# 5. How to get the documentation of the numpy add function from the command line?
# In the command line, you would use: `numpy.info(numpy.add)`, for example:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [35]:
# 6. Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [36]:
# 7. Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [37]:
# 8. Reverse a vector (first element becomes last)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [38]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(non_zero_indices)

(array([0, 1, 4]),)


In [40]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# 12. Create a 3x3x3 array with random values
random_array_3x3x3 = np.random.random((3, 3, 3))
print(random_array_3x3x3)

[[[0.13162547 0.26534343 0.03842658]
  [0.43768232 0.5367481  0.49336414]
  [0.80323802 0.1530118  0.35077148]]

 [[0.43911747 0.69982208 0.76105673]
  [0.71449964 0.43811976 0.60795531]
  [0.08470228 0.33387919 0.88884344]]

 [[0.41964903 0.9600076  0.9392022 ]
  [0.57342897 0.92543316 0.11700817]
  [0.7162085  0.38817047 0.45127518]]]


In [42]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
random_array_10x10 = np.random.random((10, 10))
min_val = random_array_10x10.min()
max_val = random_array_10x10.max()
print(f"Min: {min_val}, Max: {max_val}")

Min: 0.01802326096748319, Max: 0.9984210247108449


In [43]:
# 14. Create a random vector of size 30 and find the mean value
random_vector = np.random.random(30)
mean_val = random_vector.mean()
print(f"Mean value: {mean_val}")

Mean value: 0.5213560636422114


In [44]:
# 15. Create a 2d array with 1 on the border and 0 inside
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
# 16. How to add a border (filled with 0’s) around an existing array?
array_with_border = np.pad(array_2d, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [46]:
# 17. What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [47]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix_5x5 = np.diag(1 + np.arange(4), k=-1)
print(matrix_5x5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [48]:
# 19. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [49]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
array_6x7x8 = np.zeros((6, 7, 8))
index_100th = np.unravel_index(100, array_6x7x8.shape)
print(index_100th)

(np.int64(1), np.int64(5), np.int64(4))


In [50]:
# 21. Create a checkerboard 8x8 matrix using the tile function
checkerboard_tile = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
# 22. Normalize a 5x5 random matrix
random_matrix_5x5 = np.random.random((5, 5))
norm_matrix = (random_matrix_5x5 - np.mean(random_matrix_5x5)) / np.std(random_matrix_5x5)
print(norm_matrix)


[[ 0.97909689 -0.75079942 -1.59952212  1.04914772  1.52007643]
 [ 0.71652354  0.44557642  0.24781898  1.01672971 -1.50574192]
 [ 0.70333226 -0.53655723  1.3150146  -0.45627803  1.35079683]
 [-1.50180326  0.50980685 -0.18655764 -1.13870689 -0.36698057]
 [-0.26027329 -1.58176778  1.25204223 -0.49947975 -0.72149455]]


In [52]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color_dtype)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


In [53]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
matrix_product = np.dot(matrix_5x3, matrix_3x2)
print(matrix_product)

[[0.8624902  1.61841884]
 [0.64650449 1.19010015]
 [0.96255403 1.10557988]
 [1.05532268 1.18100751]
 [0.94773128 1.0005351 ]]


In [54]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [55]:
# 26. What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


In [63]:
# 27. Consider an integer vector Z, which of these expressions are legal?
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
print(Z < Z > Z)  # This is an illegal expression, the truth value of an array with more than one element is ambiguous.

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
# 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\lenovo\AppData\Local\Temp\ipykernel_27732\4123742269.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\lenovo\AppData\Local\Temp\ipykernel_27732\4123742269.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\lenovo\AppData\Local\Temp\ipykernel_27732\4123742269.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [58]:
# 29. How to round away from zero a float array?
float_array = np.random.uniform(-10, 10, 10)
rounded_away_from_zero = np.copysign(np.ceil(np.abs(float_array)), float_array)
print(rounded_away_from_zero)

[-7.  7. -5. -5.  9.  6.  6. -1.  7. -7.]


In [59]:
# 30. How to find common values between two arrays?
array1 = np.random.randint(0, 10, 10)
array2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(array1, array2)
print(common_values)

[0 2 4 5 7]


In [60]:
# 31. How to ignore all numpy warnings (not recommended)?
np.seterr(all="ignore")
# Ignored warnings, not recommended

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [61]:
# 32. Is the following expression true?
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [62]:
# 33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)


2024-08-18 2024-08-19 2024-08-20
